name: Build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: "*"
      - name: Install Yarn
        run: corepack enable
      - name: Install npm dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - uses: actions/upload-artifact@v3
        name: Upload Artifacts
        with:
          name: tauri-web
          path: dist/*
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: "*"
      - name: Install Yarn
        run: corepack enable
      - name: Install npm dependencies
        run: yarn install
      - name: Install tauri dependencies
        run: sudo apt update && sudo apt install -y build-essential libpython3-dev libdbus-1-dev libgtk-3-dev libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev
      - name: Build Tauri
        run: yarn run build:tauri
      - uses: actions/upload-artifact@v3
        name: Upload Artifacts (appimage)
        with:
          name: tauri-linux
          path: src-tauri/target/release/bundle/appimage/*
      - uses: actions/upload-artifact@v3
        name: Upload Artifacts (deb)
        with:
          name: tauri-debian
          path: src-tauri/target/release/bundle/deb/*
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: "*"
      - name: Install Yarn
        run: corepack enable
      - name: Install npm dependencies
        run: yarn install
      - name: Build Tauri
        run: yarn run build:tauri
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: tauri-windows
          path: src-tauri/target/release/bundle/msi/*
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: "*"
      - name: Install Yarn
        run: corepack enable
      - name: Install npm dependencies
        run: yarn install
      - name: Build Tauri
        run: yarn run build:tauri
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: tauri-macos
          path: src-tauri/target/release/bundle/macos/*
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: tauri-web
          path: ./dist/
      - uses: actions/download-artifact@master
        with:
          name: tauri-linux
          path: ./tauri-linux
      - uses: actions/download-artifact@master
        with:
          name: tauri-debian
          path: ./tauri-debian
      - uses: actions/download-artifact@master
        with:
          name: tauri-windows
          path: ./tauri-windows
      - uses: actions/download-artifact@master
        with:
          name: tauri-macos
          path: ./tauri-macos
      - name: Compress Web
        run: tar -cvzf web.tar.gz ./dist/*
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            DEPENDENCIES.txt
            README.md
            web.tar.gz
            tauri-linux/*
            tauri-debian/*
            tauri-windows/*
            tauri-macos/*

