name: Build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: *
      - name: Install Yarn
        run: corepack enable
      - name: Install npm dependencies
        run: yarn install
      - name: Build Tauri
        run: yarn run build:tauri
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: tauri
          path: src-tauri/target/release/qcvis
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: *
      - name: Install Yarn
        run: corepack enable
      - name: Install npm dependencies
        run: yarn install
      - name: Build Tauri
        run: yarn run build:tauri
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: tauri
          path: src-tauri/target/release/qcvis.exe
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: *
      - name: Install Yarn
        run: corepack enable
      - name: Install npm dependencies
        run: yarn install
      - name: Build Tauri
        run: yarn run build:tauri
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: tauri
          path: src-tauri/target/release/qcvis
